__version__ = "0.1.0"

from .actuators import ACTUATOR_PARAMETERS
from .can import FeedbackHub, Motor, drain
from .imu import (
    DEFAULT_IMU_BAUDRATE,
    DEFAULT_IMU_PORT,
    EXPECTED_UPRIGHT_GRAVITY,
    MOUNT_ROLL_DEG,
)
from .joints import (
    ACTUATED_JOINTS,
    CHANNEL_MOTOR_IDS,
    JOINT_BY_HARDWARE_NAME,
    JOINT_BY_ID,
    JOINT_BY_MODEL_NAME,
    JOINT_LIMITS_BY_ID,
    JOINT_LIMITS_BY_NAME,
    PASSIVE_CLOSED_LOOP_JOINTS,
    POLICY_JOINT_ORDER,
    JointSpec,
    channel_for_motor_id,
)
from .limits import (
    DEFAULT_LIMIT_MARGIN_RAD,
    action_normalization,
    exceeds_joint_limit,
    joint_limit_for,
)
from .motors import (
    DEFAULT_VELOCITY_ACCELERATION,
    DEFAULT_VELOCITY_LIMIT_CURRENT,
    MOTOR_CONTROL_KD,
    MOTOR_CONTROL_KP,
    MOTOR_PHYSICS,
    MOTOR_SPECS,
    PEAK_TORQUE,
    RATED_TORQUE,
    MotorSpec,
)
from .paths import (
    BALANCING_REPO_NAMES,
    COMMON_REPO_NAMES,
    DEPLOY_REPO_NAMES,
    DESCRIPTION_REPO_NAMES,
    IMU_REPO_NAMES,
    WALKING_REPO_NAMES,
    description_model,
    git_commit,
    repo_file,
    resolve_repo,
)
from .policy import PolicyContract, sha256_file
from .protocol import (
    DEFAULT_INTERFACE,
    FAULT_BIT_NAMES,
    HOST_ID,
    build_arbitration_id,
    clamp,
    decode_fault_bits,
    float_to_uint,
    parse_arbitration_id,
    uint_to_float,
)

__all__ = [
    "ACTUATED_JOINTS",
    "ACTUATOR_PARAMETERS",
    "BALANCING_REPO_NAMES",
    "CHANNEL_MOTOR_IDS",
    "COMMON_REPO_NAMES",
    "DEFAULT_IMU_BAUDRATE",
    "DEFAULT_IMU_PORT",
    "DEFAULT_INTERFACE",
    "DEFAULT_LIMIT_MARGIN_RAD",
    "DEFAULT_VELOCITY_ACCELERATION",
    "DEFAULT_VELOCITY_LIMIT_CURRENT",
    "DEPLOY_REPO_NAMES",
    "DESCRIPTION_REPO_NAMES",
    "EXPECTED_UPRIGHT_GRAVITY",
    "FAULT_BIT_NAMES",
    "FeedbackHub",
    "HOST_ID",
    "IMU_REPO_NAMES",
    "JOINT_BY_HARDWARE_NAME",
    "JOINT_BY_ID",
    "JOINT_BY_MODEL_NAME",
    "JOINT_LIMITS_BY_ID",
    "JOINT_LIMITS_BY_NAME",
    "JointSpec",
    "MOTOR_CONTROL_KD",
    "MOTOR_CONTROL_KP",
    "MOTOR_PHYSICS",
    "MOTOR_SPECS",
    "MOUNT_ROLL_DEG",
    "Motor",
    "MotorSpec",
    "PASSIVE_CLOSED_LOOP_JOINTS",
    "PEAK_TORQUE",
    "POLICY_JOINT_ORDER",
    "PolicyContract",
    "RATED_TORQUE",
    "WALKING_REPO_NAMES",
    "__version__",
    "action_normalization",
    "build_arbitration_id",
    "channel_for_motor_id",
    "clamp",
    "decode_fault_bits",
    "description_model",
    "drain",
    "exceeds_joint_limit",
    "float_to_uint",
    "git_commit",
    "joint_limit_for",
    "parse_arbitration_id",
    "repo_file",
    "resolve_repo",
    "sha256_file",
    "uint_to_float",
]
